package status

const (
	// Scheduled Mail
	MAILS_SCHEDULED       = "MAILS_SCHEDULED"
	MAILS_PROCESSING      = "MAILS_PROCESSING"
	MAILS_DELIVERED       = "MAILS_DELIVERED"
	MAILS_DELIVERY_FAILED = "MAILS_DELIVERY_FAILED"
)
