package status

const (
	POAP_REQUESTED = "POAP_REQUESTED"
	// Create GIF
	POAP_CREATE_GIF_START    = "POAP_CREATE_GIF_START"
	POAP_CREATE_GIF_COMPLETE = "POAP_CREATE_GIF_COMPLETE"
	POAP_CREATE_GIF_ERROR    = "POAP_CREATE_GIF_ERROR"
	// Mint NFT
	POAP_MINT_START    = "POAP_MINT_START"
	POAP_MINT_COMPLETE = "POAP_MINT_COMPLETE"
	POAP_MINT_ERROR    = "POAP_MINT_ERROR"
	// Mail
	POAP_MAILER_START    = "POAP_MAILER_START"
	POAP_MAILER_COMPLETE = "POAP_MAILER_COMPLETE"
	POAP_MAILER_ERROR    = "POAP_MAILER_ERROR"
)
